language: julia

os:
  - osx
  - linux
  - windows

# hack to get some OS-specific badges
env:
  - BADGE=linux
  - BADGE=osx
  - BADGE=windows

julia:
  - 1.0
  - 1.3
  - nightly

codecov: true

notifications:
  email: false

jobs:
  exclude:
    - os: linux
      env: 
        - BADGE=osx
        - BADGE=windows
    - os: osx
      env: 
        - BADGE=linux
        - BADGE=windows
    - os: windows
      env: 
        - BADGE=osx
        - BADGE=linux
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: osx
      script: julia --project=docs --color=yes -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip

