language: julia

os:
  - osx
  - linux
  - windows

julia:
  - 1.0
  - 1.3
  - nightly

codecov: true

notifications:
  email: false

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.3
      os: osx
      script: julia --project=docs --color=yes -e '
          using Pkg;
          Pkg.develop(PackageSpec(path=pwd()));
          Pkg.instantiate();
          include("docs/make.jl");'
      after_success: skip

